services:
  nginx:
    image: proelkady/catchup-nginx:0.1.18
    restart: unless-stopped
    container_name: catchup-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - keycloak
      - wordpress
    networks:
      - catchup-network

  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: catchup-postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: "K59{4b)dS#dIQRbX"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catchup-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: catchup-keycloak
    restart: unless-stopped
    command: start-dev --proxy-headers xforwarded --hostname-strict=false
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: "K59{4b)dS#dIQRbX"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-password00))!
      KC_HOSTNAME: auth-dev.catchup-app.app
      KC_HOSTNAME_PORT: -1
      KC_PROXY: edge
    depends_on:
      - postgres
    networks:
      - catchup-network

  mongodb:
    image: mongo:6
    restart: unless-stopped
    container_name: catchup-mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - catchup-network

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: catchup-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: UE!rPygb*nnqkX2ePe_p
      MYSQL_DATABASE: catchup-dev
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - catchup-network

  wordpress:
    image: wordpress:6.7.1
    restart: unless-stopped
    container_name: catchup-wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress-admin
      WORDPRESS_DB_PASSWORD: NUUyhHDyE9w!fbcG8AQg
      WORDPRESS_DB_NAME: wordpress-site
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    networks:
      - catchup-network
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - catchup-network

  redocly:
    image: redocly/redoc:latest
    container_name: catchup-redocly
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      SPEC_URL: https://api-dev.catchup-app.app/docs/example-api
    networks:
      - catchup-network

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: catchup-oauth2-proxy
    restart: unless-stopped
    command:
      - --provider=oidc
      - --provider-display-name=Keycloak
      - --client-id=docs-client
      - --client-secret=ynYlwNFzaVbjnu8qaVrkJGYJl1TviCe0
      - --redirect-url=https://docs-dev.catchup-app.app/oauth2/callback
      - --oidc-issuer-url=https://auth-dev.catchup-app.app/realms/catchup-docs
      - --ssl-insecure-skip-verify=true
      - --cookie-secret=d5a64903d38b4d80869ffcf47aa5ae9e
      - --email-domain=*
      - --upstream=http://redocly:80
      - --http-address=0.0.0.0:4180
      - --cookie-secure=true
      - --cookie-expire=24h
      - --skip-provider-button=true
      - --insecure-oidc-skip-issuer-verification=true
      - --code-challenge-method=S256
      - --insecure-oidc-allow-unverified-email=true
    depends_on:
      - redocly
      - keycloak
    networks:
      - catchup-network

networks:
  catchup-network:
    external: true

volumes:
  postgres_data:
  mongo_data:
  mysql_data:
  wordpress_data:
  redis-data:
